Cdsupina/motion2d refactor
amethyst/space_shooter_rs pull request #105
Opened 2021-01-18 08:06 UTC by cdsupina

General motion in Motion2DSystem

Enemy motion in EnemyMotion2DSystem.

2021-01-19 02:54 UTC, tigleym requested changes
Thanks! It's looking good so far. I just had some questions about the magic numbers being used for the enemy motion system.

2021-01-19 02:54 UTC, tigleym commented on src/systems/motion2d.rs
> +            if transform.translation().y > ARENA_MIN_Y + ARENA_HEIGHT - 30.0 {
Is 30.0 an offset value of the enemy's hitbox? How are you getting this number?

2021-01-19 02:54 UTC, tigleym commented on src/systems/motion2d.rs
> +            if transform.translation().y > ARENA_MIN_Y + ARENA_HEIGHT - 67.0 {
Same as above.

2021-01-19 02:54 UTC, tigleym commented on src/systems/motion2d.rs
> +            if transform.translation().y > ARENA_MIN_Y + ARENA_HEIGHT - 32.0 {
same as above

2021-01-19 03:40 UTC, cdsupina commented on src/systems/motion2d.rs
> +            if transform.translation().y > ARENA_MIN_Y + ARENA_HEIGHT - 30.0 {
These were used in the previous enemy.rs system as well. These arbitrary numbers just indicate a position on the y axis in the arena. Once the parts reach the arbitrary position they stop accelerating downward and reverse acceleration in the other direction resulting in the oscillation. These arbitrary numbers line each of the boss parts up with each other to make it appear that the boss is one cohesive unit.

2021-01-19 03:42 UTC, cdsupina commented on src/systems/motion2d.rs
> +            if transform.translation().y > ARENA_MIN_Y + ARENA_HEIGHT - 30.0 {
I think we should leave this as is until we work on the boss part hierarchy.

2021-01-20 02:13 UTC, tigleym approved these changes
Thanks! LGTM.

2021-01-20 02:58 UTC, merged