Add documentation for Entities and Components in space_shooter_rs
amethyst/space_shooter_rs pull request #88
Opened 2020-10-15 22:42 UTC by tigleym

For #83  

This PR adds a section describing the `Spaceship`, `Enemy`, and `Item` entities and their attached components.

2020-10-16 04:09 UTC, cdsupina requested changes
Left some suggestions on grammar. More importantly, I left a comment on the consistency of using the "-Component" suffix at the end of the component names. Let me know what you think.

2020-10-16 04:09 UTC, cdsupina commented on book/src/entities-components.md
> +We will look at three entities present in space_shooter_rs: `Spaceship`
I think that referring to components without the word "Component" at the end (as in `ItemComponent`) is fine. However, we should maybe make a note in this book that our naming convention for our custom components is to have "Component" at the end. I also think that now may be the time to make all of the other components in the game, such as `Spaceship` and `Enemy` be consistent with the rest of the new components that we added and change them to `SpaceshipComponent` and `EnemyComponent`. I think that staying consistent is really important to helping new people learn the code.

2020-10-16 04:09 UTC, cdsupina commented on book/src/entities-components.md
> +pub struct Item {
```suggestion
pub struct ItemComponent {
```
I changed this in #87.

2020-10-16 04:09 UTC, cdsupina commented on book/src/entities-components.md
> +Again this seems like a lot of components for only three entities. But if we keep
```suggestion
Again, this seems like a lot of components for only three entities. But if we keep
```

2020-11-06 00:20 UTC, tigleym commented
Thanks @cdsupina for the review! I've addressed your suggestions:

- Made sure all components had "Component" at the end of their name
- Added some pictures for the architecture.md file
- Added extra content on naming conventions for Custom and Tag components

2020-11-10 02:04 UTC, cdsupina approved these changes
Looks great! Go ahead and merge! I love the inclusion of the graphics from our talk at RustFest!

2020-11-10 03:55 UTC, merged